module.exports = {
  SERVER_URL: process.env.NEXT_PUBLIC_SERVER_URL,
  CLIENT_ID: process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID,

  DATABASE_URL: process.env.NEXT_PUBLIC_MONGODB_URI,
  JWT_SECRET: process.env.NEXT_PUBLIC_JWT_SECRET,
};
